[package]
name = "c24-to-ynab"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.7", features = ["multipart"] }
chrono = "0.4.38"
csv = "1.3.0"
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = "0.7.12"
